version: '3.8'

services:
  db:
    image: postgres:13-alpine
    volumes:
      - pg_data:/var/lib/postgresql/data/
      - ./docker_postgres_init.sql:/docker-entrypoint-initdb.d/docker_postgres_init.sql
    env_file:
      - ./pg_settings_dev.env
    ports:
      - 15432:5432
    restart: unless-stopped

volumes:
  pg_data:
