version: '3.8'

services:
  db:
    image: postgres:13-alpine
    volumes:
      - pg_data:/var/lib/postgresql/data/
    env_file:
      - ./pg_settings_dev.env
    ports:
      - 5432:5432

volumes:
  pg_data:
